### ISSUE TITLE
Nelle tabelle del registro modifiche generate dal template, l'allineamento orizzontale della versione è a destra

### ISSUE THREAD

**Issue by stoccotommaso02** [Argo-swe/Docs#11]
Il comportamento preferibile sarebbe centrato, come il resto delle colonne della tabella

**Comment by Rikicavaz77** [comment]
`Esempio`: 

![image](https://github.com/Argo-swe/Docs/assets/120377343/b5b2d115-736c-48bd-ba1a-ff0cec779aa4)

**Comment by Rikicavaz77** [comment]
`Esempio di soluzione`: @stoccotommaso02 @mzecchinato 

![image](https://github.com/Argo-swe/Docs/assets/120377343/a30d1168-0c7c-4153-a325-8b9949ee4d8f)

**Comment by Rikicavaz77** [comment]
`Soluzione proposta`

![image](https://github.com/Argo-swe/Docs/assets/120377343/25c1e420-ec8b-4827-add1-a0892ffa36ed)

@mzecchinato @stoccotommaso02 Ho preso come riferimento la riga dell'header, ma i margini a destra e sinistra in che documento sono specificati?
