### ISSUE TITLE
Stesura bozza AdR - Introduzione + Scopo del prodotto + Tecnologie

### ISSUE THREAD

**Issue by Rikicavaz77** [Argo-swe/Docs#23]
Stesura <ins>**BOZZA**</ins> del documento di `Analisi dei Requisiti`, con:

- [x] Introduzione;
- [x] Scopo del documento;
- [x] Scopo del prodotto;
- [x] Riferimenti.

Individuazione delle `tecnologie`, soprattutto per la sezione inerente lo sviluppo della `web app`, da proporre durante la riunione con la Proponente.

**Comment by CristoMarco** [comment]
Lo Scopo del prodotto è stato abbozzato, mentre  è stata completata la prima stesura delle sezioni di Introduzione, Scopo del documento e Riferimenti.
