### ISSUE TITLE
Stesura bozza AdR - Requisiti minimi

### ISSUE THREAD

**Issue by Rikicavaz77** [Argo-swe/Docs#24]
Stesura <ins>**BOZZA**</ins> del documento di `Analisi dei requisiti`, con:

- [x] Attori;
- [x] Caratteristiche degli utenti;
- [x] Casi d'uso (il focus è sui requisiti minimi obbligatori).

**Comment by Rikicavaz77** [comment]
@martinaamico @LewentalDigital In attesa di capire come muoverci con l'ITS, se riuscite entro lunedì ad aggiungere uno / due commenti qui per spiegare cosa avete fatto. Così poi chiudiamo l'Issue e ne apriamo un altro per la conversione in LaTeX.

**Comment by LewentalDigital** [comment]
> @martinaamico @LewentalDigital In attesa di capire come muoverci con l'ITS, se riuscite entro lunedì ad aggiungere uno / due commenti qui per spiegare cosa avete fatto. Così poi chiudiamo l'Issue e ne apriamo un altro per la conversione in LaTeX.

Oltre alla strutturazione e alla stesura iniziale delle sezioni del documento ci siamo concentrati sui casi d'uso.
La struttura del documento segue quella indicata da IEEE che ha trovato Marco, e anche un po i documenti degli altri gruppi

Questa e la struttura che abbiamo creato:
1) Introduzione
 1.1) Scopo/Obiettivo del documento
  1.1.1) Struttura logica casi d'uso
 1.2) Scopo del prodotto
 1.3) Glossario
 1.4) Riferimenti
  1.4.1) Riferimenti normativi
  1.4.2) Riferimenti informativi
2) Descrizione 
 2.1) Obiettivi fissati/Obiettivi del prodotto
 2.2) Funzioni del prodotto
 2.3) Caratteristiche del prodotto
  2.3.1) [Utenti di Zucchetti]
  2.3.2) [Utenti del nostro prodotto]
 2.4) Tecnologie e analisi della struttura di progetto
3) Casi d'uso
 3.1) Obiettivi/Scopo
 3.2) Introduzione ai casi d'uso
 3.3) Attori
  3.3.1) [Dettagli aggiuntivi]
 3.4) Gestione degli errori
 3.5) Elenco dei casi d'uso
4) Requisiti
 4.1) Requisiti funzionali
 4.2) Requisiti di qualità/Requisiti qualitativi
 4.3) Requisiti di vincolo
  4.3.1) Requisiti di prestazione
  4.3.2) Requisiti browser
  4.3.3) Requisiti di sicurezza
 4.5) Tracciamento
  4.5.1) Fonti - Requisiti
 4.6) Riepilogo
5) Conclusioni
 
I casi d'uso principali sono:
UC1 - Autenticazione
UC3 - Inserimento richiesta in linguaggio naturale 
UC4 - selezione dizionario dati
UC5 - generazione prompt 
UC7 - cambia lingua
UC8 - Selezione prompt risultato
UC9 - Visualizzazione lista dizionario dati
UC11 - Visualizzazione frase SQL (opzionale)
UC12 - Logout
UC13 - Caricamento dizionario dati
UC14 - Visualizzazione dati dizionario
UC15 - Verifica correttezza dizionario
UC16 - Modifica dizionario dati
UC18 - Debug della generazione del prompti

Abbamo inoltre sviluppato tutti i sotto casi e gli extends come ad esempio errori

Ogni caso d'uso e' completo di UML
